#!/bin/bash

CONFIG_FILE="./vmconfig.conf"

echo "[*] Running VM environment setup..."

# Prompt for base VM and output path
read -p "Enter path to your VM template (default: /mnt/d/vms/template): " BASE_VM
BASE_VM="${BASE_VM:-/mnt/d/vms/template}"

read -p "Enter output directory for created VMs (default: /mnt/d/vms/instances): " VM_OUTPUT_DIR
VM_OUTPUT_DIR="${VM_OUTPUT_DIR:-/mnt/d/vms/instances}"

# Set default vmrun path
DEFAULT_VMRUN="/mnt/c/Program Files (x86)/VMware/VMware Workstation/vmrun.exe"
read -p "Enter full path to vmrun (default: $DEFAULT_VMRUN): " VMRUN
VMRUN="${VMRUN:-$DEFAULT_VMRUN}"

# Check dependencies
DEPS=(genisoimage uuidgen wslpath qemu-img)
MISSING=()
for cmd in "${DEPS[@]}"; do
  if ! command -v "$cmd" &> /dev/null; then
    MISSING+=("$cmd")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "[!] Missing dependencies: ${MISSING[*]}"
  echo "    Please install them (e.g. apt install genisoimage uuid-runtime qemu-utils)"
  exit 1
fi

read -p "Enter default username for VMs (default: victim): " USERNAME
USERNAME="${USERNAME:-victim}"

DEFAULT_SSH_KEY_PATH="$HOME/.ssh/id_rsa"
read -p "Enter path to SSH public key (default: $DEFAULT_SSH_KEY_PATH): " SSH_KEY_PATH
SSH_KEY_PATH="${SSH_KEY_PATH:-$DEFAULT_SSH_KEY_PATH}"

if [[ ! -f "$SSH_KEY_PATH" ]]; then
  echo "[!] SSH key not found at: $SSH_KEY_PATH"
  exit 1
fi

# Write config
cat > "$CONFIG_FILE" <<EOF
# Generated by setup.sh

BASE_VM="$BASE_VM"
VM_OUTPUT_DIR="$VM_OUTPUT_DIR"
VMRUN="$VMRUN"
USERNAME="$USERNAME"
SSH_KEY_PATH="$SSH_KEY_PATH"
TEMPLATE_DIR="./template"
EOF

echo "[+] Setup complete. Config saved to $CONFIG_FILE"


